version: "3.7"

services:
  users-app:
    image: leo/users_api:v1
    ports:
      - "5050:5000"
    depends_on:
      - mysql

  catalogue:
    image: leo/catalogue:v1
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.24
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yolo
      MYSQL_DATABASE: users

volumes:
  mysql-data:
